# Generated by Django 5.2.8 on 2025-11-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporada',
            old_name='año',
            new_name='anyo',
        ),
    ]
