# Generated by Django 5.2.8 on 2025-11-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_rename_año_temporada_anyo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_visitante',
            new_name='visitante',
        ),
    ]
