# Generated by Django 5.2.8 on 2025-11-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_rename_equipo_local_partido_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.jornada'),
        ),
    ]
